### ISSUE TITLE
Wrong User Account (Windows 8)

### ISSUE THREAD

**Issue by schmitch** [rgl/elasticsearch-setup#9] opened 2013-09-09 10:18 UTC
After installing Elasticsearch with Elasticsearch-setup on Windows 8 the Service has a wrong Useraccount. it always tries to start the service as elasticsearch User which doesn't exists on Windows 8. I needed to switch it to Local System.

**Comment by rgl** [comment] 2015-06-19 06:51
Closing this as I can't reproduce the issue.

**Closed by rgl** 2015-06-19 06:51 UTC
